
spring:
  application:
    name: customer-services
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop